export const SET_PROJECT_CATEGORY = 'SET_PROJECT_CATEGORY';
export const SET_LIST_PROJECT = 'SET_LIST_PROJECT';
export const SET_PROJECT_UPDATE = 'SET_PROJECT_UPDATE';
export const SET_PROJECT_DETAIL = 'SET_PROJECT_DETAIL';